
import type { App } from './types';

export const defaultApps: App[] = [
  { id: 'sonic-1', name: 'LPB Sonic', url: 'https://lpbsonic.xyz/', iconUrl: 'https://icon.horse/icon/lpbsonic.xyz', category: 'DeFi', isCustom: false, isFavorite: true },
  { id: 'sonic-2', name: 'Heyanon', url: 'https://heyanon.ai/', iconUrl: 'https://icon.horse/icon/heyanon.ai', category: 'AI', isCustom: false, isFavorite: true },
  { id: 'sonic-3', name: 'Equalizer', url: 'https://equalizer.exchange/', iconUrl: 'https://icon.horse/icon/equalizer.exchange', category: 'DEX', isCustom: false, isFavorite: true },
  { id: 'sonic-4', name: 'Shadow Exchange', url: 'https://www.shadow.so/', iconUrl: 'https://icon.horse/icon/shadow.so', category: 'Dex', isCustom: false, isFavorite: true },
  { id: 'sonic-5', name: 'DeFive', url: 'https://defive.com/', iconUrl: 'https://icon.horse/icon/defive.com', category: 'DeFi', isCustom: false, isFavorite: true },
  { id: 'sonic-6', name: 'Beets', url: 'https://beets.fi/', iconUrl: 'https://icon.horse/icon/beets.fi', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-7', name: 'Fly Trade', url: 'https://www.fly.trade/', iconUrl: 'https://icon.horse/icon/fly.trade', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-8', name: 'Metropolis', url: 'https://metropolis.exchange/', iconUrl: 'https://icon.horse/icon/metropolis.exchange', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-9', name: 'PaintSwap IO', url: 'https://paintswap.io/', iconUrl: 'https://icon.horse/icon/paintswap.io', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-10', name: 'Navigator Exchange', url: 'https://www.navigator.exchange/#/', iconUrl: 'https://icon.horse/icon/navigator.exchange', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-11', name: 'Snake Finance', url: 'https://snake.finance/', iconUrl: 'https://icon.horse/icon/snake.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-12', name: 'SwapX', url: 'https://swapx.fi/', iconUrl: 'https://icon.horse/icon/swapx.fi', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-13', name: 'Derpe', url: 'https://derpe.xyz/', iconUrl: 'https://icon.horse/icon/derpe.xyz', category: 'Memes', isCustom: false, isFavorite: false },
  { id: 'sonic-14', name: 'Tin Hat Cat', url: 'https://www.tinhatcat.com/', iconUrl: 'https://icon.horse/icon/tinhatcat.com', category: 'Memes', isCustom: false, isFavorite: false },
  { id: 'sonic-15', name: 'Goglz', url: 'https://goglz.io/', iconUrl: 'https://icon.horse/icon/goglz.io', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-16', name: 'Wagmi', url: 'https://wagmi.com/', iconUrl: 'https://icon.horse/icon/wagmi.com', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-17', name: 'Spinit', url: 'https://spinit.owl.games/', iconUrl: 'https://icon.horse/icon/spinit.owl.games', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-18', name: 'FaGame', url: 'https://fagame.org/', iconUrl: 'https://icon.horse/icon/fagame.org', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-19', name: 'Boom Markets', url: 'https://boom.markets/', iconUrl: 'https://icon.horse/icon/boom.markets', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-20', name: '8finity', url: 'https://8finity.xyz/', iconUrl: 'https://icon.horse/icon/8finity.xyz', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-21', name: 'Stability Farm', url: 'https://stability.farm/', iconUrl: 'https://icon.horse/icon/stability.farm', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-22', name: 'Lumos Coin', url: 'https://lumoscoin.com/', iconUrl: 'https://icon.horse/icon/lumoscoin.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-23', name: 'SNS', url: 'https://sns.net/', iconUrl: 'https://icon.horse/icon/sns.net', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-24', name: 'Hedgy Sonic', url: 'https://hedgysonic.com/', iconUrl: 'https://icon.horse/icon/hedgysonic.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-25', name: 'Indisonic', url: 'https://www.indisonic.xyz/', iconUrl: 'https://icon.horse/icon/indisonic.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-26', name: 'Myrd Sacra', url: 'https://myrd.sacra.game/', iconUrl: 'https://icon.horse/icon/myrd.sacra.game', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-27', name: 'SpookySwap', url: 'https://www.spooky.fi/', iconUrl: 'https://icon.horse/icon/spooky.fi', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-28', name: 'Eggs Finance', url: 'https://eggs.finance/', iconUrl: 'https://icon.horse/icon/eggs.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-29', name: 'Sonic Whale', url: 'https://sonicwhale.ai/', iconUrl: 'https://icon.horse/icon/sonicwhale.ai', category: 'AI', isCustom: false, isFavorite: false },
  { id: 'sonic-30', name: 'DeBank', url: 'https://debank.com/', iconUrl: 'https://icon.horse/icon/debank.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-31', name: 'DexScreener', url: 'https://dexscreener.com/', iconUrl: 'https://icon.horse/icon/dexscreener.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-32', name: 'Ruggie\'s Pizza', url: 'https://games.ruggiespizza.com/', iconUrl: 'https://icon.horse/icon/games.ruggiespizza.com', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-33', name: 'deBridge Finance', url: 'https://debridge.finance/', iconUrl: 'https://icon.horse/icon/debridge.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-34', name: 'Silo Finance', url: 'https://www.silofinance.com/', iconUrl: 'https://icon.horse/icon/silofinance.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-35', name: 'Avalon Labs', url: 'https://www.avalonlabs.io/', iconUrl: 'https://icon.horse/icon/avalonlabs.io', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-36', name: 'Aave', url: 'https://www.aave.com/', iconUrl: 'https://icon.horse/icon/aave.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-37', name: 'Vicuna Finance', url: 'https://vicunafinance.com/', iconUrl: 'https://icon.horse/icon/vicunafinance.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-38', name: 'Curve', url: 'https://curve.fi/', iconUrl: 'https://icon.horse/icon/curve.fi', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-39', name: 'Yearn Finance', url: 'https://yearn.fi/', iconUrl: 'https://icon.horse/icon/yearn.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-40', name: 'Stryke', url: 'https://www.stryke.xyz/', iconUrl: 'https://icon.horse/icon/stryke.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-41', name: 'Rings Money', url: 'https://rings.money/', iconUrl: 'https://icon.horse/icon/rings.money', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-42', name: 'MachFi', url: 'https://www.machfi.xyz/', iconUrl: 'https://icon.horse/icon/machfi.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-43', name: 'SilverSwap', url: 'https://silverswap.io/', iconUrl: 'https://icon.horse/icon/silverswap.io', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-44', name: 'YEL Finance', url: 'https://yel.finance/', iconUrl: 'https://icon.horse/icon/yel.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-45', name: 'MarginZero', url: 'https://www.marginzero.xyz/', iconUrl: 'https://icon.horse/icon/marginzero.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-46', name: 'Thunderdome', url: 'https://thunderdome.so/#', iconUrl: 'https://icon.horse/icon/thunderdome.so', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-47', name: 'Kyber Network', url: 'https://kyber.network/', iconUrl: 'https://icon.horse/icon/kyber.network', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-48', name: 'Krown Labs', url: 'https://www.krownlabs.app/', iconUrl: 'https://icon.horse/icon/krownlabs.app', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-49', name: 'Origin Protocol', url: 'https://www.originprotocol.com/', iconUrl: 'https://icon.horse/icon/originprotocol.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-50', name: 'Curve (Sonic)', url: 'https://www.curve.finance/dex/sonic/pools/', iconUrl: 'https://icon.horse/icon/curve.finance', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-51', name: 'Chainspect', url: 'https://chainspect.app/', iconUrl: 'https://icon.horse/icon/chainspect.app', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-52', name: 'Rhino.fi', url: 'https://rhino.fi/', iconUrl: 'https://icon.horse/icon/rhino.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-53', name: 'Snapshot', url: 'https://snapshot.org/', iconUrl: 'https://icon.horse/icon/snapshot.org', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-54', name: 'Odos', url: 'https://app.odos.xyz/', iconUrl: 'https://icon.horse/icon/odos.xyz', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-55', name: 'Alchemy', url: 'https://alchemy.com/', iconUrl: 'https://icon.horse/icon/alchemy.com', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-56', name: 'Summer.fi', url: 'https://summer.fi/', iconUrl: 'https://icon.horse/icon/summer.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-57', name: 'Micro3', url: 'https://micro3.io/', iconUrl: 'https://icon.horse/icon/micro3.io', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-58', name: 'Tenderly', url: 'https://tenderly.co/', iconUrl: 'https://icon.horse/icon/tenderly.co', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-59', name: 'Eliteness', url: 'https://eliteness.network/', iconUrl: 'https://icon.horse/icon/eliteness.network', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-60', name: 'Multisender', url: 'https://classic.multisender.app/', iconUrl: 'https://icon.horse/icon/multisender.app', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-61', name: 'Magpie', url: 'https://www.magpiefi.xyz/', iconUrl: 'https://icon.horse/icon/magpiefi.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-62', name: 'Sushi (Sonic)', url: 'https://www.sushi.com/sonic/swap', iconUrl: 'https://icon.horse/icon/sushi.com', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-63', name: 'Yoko', url: 'https://yoko.live/', iconUrl: 'https://icon.horse/icon/yoko.live', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-64', name: 'Arkham', url: 'https://intel.arkm.com/', iconUrl: 'https://icon.horse/icon/arkm.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-65', name: 'Spectra', url: 'https://app.spectra.finance/pools', iconUrl: 'https://icon.horse/icon/spectra.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-66', name: 'TRM Labs', url: 'https://www.trmlabs.com/', iconUrl: 'https://icon.horse/icon/trmlabs.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-67', name: 'Euler Finance', url: 'https://www.euler.finance/', iconUrl: 'https://icon.horse/icon/euler.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-68', name: 'Napier Finance', url: 'https://napier.finance/', iconUrl: 'https://icon.horse/icon/napier.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-69', name: 'sNFT', url: 'https://snft.pro/', iconUrl: 'https://icon.horse/icon/snft.pro', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-70', name: 'LND Fi', url: 'https://www.lnd.fi/', iconUrl: 'https://icon.horse/icon/lnd.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-71', name: 'WooFi', url: 'https://woofi.com/', iconUrl: 'https://icon.horse/icon/woofi.com', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-72', name: 'OnFinality', url: 'https://www.onfinality.me/', iconUrl: 'https://icon.horse/icon/onfinality.me', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-73', name: 'Chainsight', url: 'https://chainsight.network/', iconUrl: 'https://icon.horse/icon/chainsight.network', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-74', name: 'Ichi', url: 'https://www.ichi.org/', iconUrl: 'https://icon.horse/icon/ichi.org', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-75', name: 'Lynx Finance', url: 'https://www.lynx.finance/', iconUrl: 'https://icon.horse/icon/lynx.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-76', name: 'OpenOcean', url: 'https://app.openocean.finance/', iconUrl: 'https://icon.horse/icon/openocean.finance', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-77', name: 'Biconomy', url: 'https://www.biconomy.io/', iconUrl: 'https://icon.horse/icon/biconomy.io', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-78', name: 'Solv Finance', url: 'https://solv.finance/', iconUrl: 'https://icon.horse/icon/solv.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-79', name: 'ZNS Connect', url: 'https://www.znsconnect.io/', iconUrl: 'https://icon.horse/icon/znsconnect.io', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-80', name: 'Owlto Finance', url: 'https://owlto.finance/', iconUrl: 'https://icon.horse/icon/owlto.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-81', name: 'Project Zero', url: 'https://projectzero.io/', iconUrl: 'https://icon.horse/icon/projectzero.io', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-82', name: 'Beefy', url: 'https://beefy.com/', iconUrl: 'https://icon.horse/icon/beefy.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-83', name: 'Safe', url: 'https://safe.global/', iconUrl: 'https://icon.horse/icon/safe.global', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-84', name: 'MCLB', url: 'https://mclb.org/', iconUrl: 'https://icon.horse/icon/mclb.org', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-85', name: 'DexFi', url: 'https://dexfi.com/', iconUrl: 'https://icon.horse/icon/dexfi.com', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-86', name: 'EncLabs Finance', url: 'https://enclabs.finance/', iconUrl: 'https://icon.horse/icon/enclabs.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-87', name: 'Band Protocol', url: 'https://www.bandprotocol.com/', iconUrl: 'https://icon.horse/icon/bandprotocol.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-88', name: 'Envio', url: 'https://envio.dev/', iconUrl: 'https://icon.horse/icon/envio.dev', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-89', name: 'SideShift.ai', url: 'https://sideshift.ai/', iconUrl: 'https://icon.horse/icon/sideshift.ai', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-90', name: 'SuperSonic', url: 'https://www.supersonic.trade/', iconUrl: 'https://icon.horse/icon/supersonic.trade', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-91', name: 'Stargate Finance', url: 'https://stargate.finance/', iconUrl: 'https://icon.horse/icon/stargate.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-92', name: 'Frax Finance', url: 'https://frax.finance/', iconUrl: 'https://icon.horse/icon/frax.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-93', name: 'Astrolescent', url: 'https://astrolescent.com/bridge', iconUrl: 'https://icon.horse/icon/astrolescent.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-94', name: 'Meson', url: 'https://meson.fi/', iconUrl: 'https://icon.horse/icon/meson.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-95', name: 'Estfor', url: 'https://estfor.com/', iconUrl: 'https://icon.horse/icon/estfor.com', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-96', name: 'CrossCurve', url: 'https://app.crosscurve.fi/swap', iconUrl: 'https://icon.horse/icon/crosscurve.fi', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-97', name: 'SimpleSwap', url: 'https://simpleswap.io/', iconUrl: 'https://icon.horse/icon/simpleswap.io', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-98', name: 'Bungee', url: 'https://new.bungee.exchange/', iconUrl: 'https://icon.horse/icon/bungee.exchange', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-99', name: 'Gamma', url: 'https://www.gamma.xyz/', iconUrl: 'https://icon.horse/icon/gamma.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-100', name: 'LlamaPay', url: 'https://llamapay.io/', iconUrl: 'https://icon.horse/icon/llamapay.io', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-101', name: 'Gasp', url: 'https://www.gasp.xyz/', iconUrl: 'https://icon.horse/icon/gasp.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-102', name: 'Solidly', url: 'https://solidly.com/', iconUrl: 'https://icon.horse/icon/solidly.com', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-103', name: 'Fireblocks', url: 'https://www.fireblocks.com/', iconUrl: 'https://icon.horse/icon/fireblocks.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-104', name: 'Sonic Market', url: 'https://www.sonic.market/', iconUrl: 'https://icon.horse/icon/sonic.market', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-105', name: 'Layer3', url: 'https://app.layer3.xyz/', iconUrl: 'https://icon.horse/icon/layer3.xyz', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-106', name: 'Oku Trade', url: 'https://oku.trade/', iconUrl: 'https://icon.horse/icon/oku.trade', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-107', name: 'TokenPocket', url: 'https://www.tokenpocket.pro/', iconUrl: 'https://icon.horse/icon/tokenpocket.pro', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-108', name: 'Portals', url: 'https://www.portals.fi/', iconUrl: 'https://icon.horse/icon/portals.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-109', name: 'Yelay', url: 'https://app.yelay.io/sonic', iconUrl: 'https://icon.horse/icon/yelay.io', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-110', name: 'Paladin', url: 'https://paladin.vote/#/', iconUrl: 'https://icon.horse/icon/paladin.vote', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-111', name: 'Perq Finance', url: 'https://dev.perq.finance/pods/SONIC', iconUrl: 'https://icon.horse/icon/perq.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-112', name: 'BlazingBot', url: 'https://app.blazingbot.com/dashboard/pro/sonic', iconUrl: 'https://icon.horse/icon/blazingbot.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-113', name: 'Vertex Protocol', url: 'https://vertexprotocol.com/', iconUrl: 'https://icon.horse/icon/vertexprotocol.com', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-114', name: 'vfat.tools', url: 'https://vfat.io/', iconUrl: 'https://icon.horse/icon/vfat.io', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-115', name: 'OpenBlock Labs', url: 'https://www.openblocklabs.com/', iconUrl: 'https://icon.horse/icon/openblocklabs.com', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-116', name: 'Symbiosis', url: 'https://app.symbiosis.finance/', iconUrl: 'https://icon.horse/icon/symbiosis.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-117', name: 'Pendle Finance', url: 'https://www.pendle.finance/', iconUrl: 'https://icon.horse/icon/pendle.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-118', name: 'Blockchain Bureau', url: 'https://blockchainbureau.com/', iconUrl: 'https://icon.horse/icon/blockchainbureau.com', category: 'Education', isCustom: false, isFavorite: false },
  { id: 'sonic-119', name: 'Sacra Game', url: 'https://sacra.game/', iconUrl: 'https://icon.horse/icon/sacra.game', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-120', name: 'Avalon Finance', url: 'https://www.avalonfinance.xyz/', iconUrl: 'https://icon.horse/icon/avalonfinance.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-121', name: 'fMoney Market', url: 'https://www.fmoney.market/', iconUrl: 'https://icon.horse/icon/fmoney.market', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-122', name: 'Sparta', url: 'https://sparta.my/', iconUrl: 'https://icon.horse/icon/sparta.my', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-123', name: 'Allora Network', url: 'https://allora.network/', iconUrl: 'https://icon.horse/icon/allora.network', category: 'AI', isCustom: false, isFavorite: false },
  { id: 'sonic-124', name: 'Swaps.io', url: 'https://swaps.io/', iconUrl: 'https://icon.horse/icon/swaps.io', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-125', name: 'Router Nitro', url: 'https://app.routernitro.com/', iconUrl: 'https://icon.horse/icon/routernitro.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-126', name: 'Dune', url: 'https://dune.com/home', iconUrl: 'https://icon.horse/icon/dune.com', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-127', name: 'Sentio', url: 'https://www.sentio.xyz/', iconUrl: 'https://icon.horse/icon/sentio.xyz', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-128', name: 'Orderly Network', url: 'https://orderly.network/', iconUrl: 'https://icon.horse/icon/orderly.network', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-129', name: 'Amped Finance', url: 'https://amped.finance/', iconUrl: 'https://icon.horse/icon/amped.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-130', name: 'Steer Finance', url: 'https://steer.finance/', iconUrl: 'https://icon.horse/icon/steer.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-131', name: 'NFTs2Me', url: 'https://nfts2me.com/', iconUrl: 'https://icon.horse/icon/nfts2me.com', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-132', name: 'Lazy Bear', url: 'https://lazybear.cc/', iconUrl: 'https://icon.horse/icon/lazybear.cc', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-133', name: 'Angles', url: 'https://angles.fi/', iconUrl: 'https://icon.horse/icon/angles.fi', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-134', name: 'HyperSonic Exchange', url: 'https://hypersonic.exchange/', iconUrl: 'https://icon.horse/icon/hypersonic.exchange', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-135', name: 'Web3Auth', url: 'https://web3auth.io/', iconUrl: 'https://icon.horse/icon/web3auth.io', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-136', name: 'Rubic', url: 'https://rubic.exchange/', iconUrl: 'https://icon.horse/icon/rubic.exchange', category: 'DEX', isCustom: false, isFavorite: false },
];

export const appHints: Record<string, string> = {
  'LPB Sonic': 'defi protocol',
  'Heyanon': 'ai social',
  'Equalizer': 'decentralized exchange',
  'Shadow Exchange': 'decentralized exchange',
  'DeFive': 'defi protocol',
  'Beets': 'decentralized exchange',
  'Fly Trade': 'decentralized exchange',
  'Metropolis': 'decentralized exchange',
  'PaintSwap IO': 'nft marketplace',
  'Navigator Exchange': 'decentralized exchange',
  'Snake Finance': 'defi protocol',
  'SwapX': 'decentralized exchange',
  'Derpe': 'meme coin',
  'Tin Hat Cat': 'meme coin',
  'Goglz': 'web3 utilities',
  'Wagmi': 'web3 developer',
  'Spinit': 'web3 game',
  'FaGame': 'web3 game',
  'Boom Markets': 'defi trading',
  '8finity': 'web3 platform',
  'Stability Farm': 'defi yield',
  'Lumos Coin': 'crypto coin',
  'SNS': 'social name service',
  'Hedgy Sonic': 'defi protocol',
  'Indisonic': 'defi protocol',
  'Myrd Sacra': 'web3 game',
  'SpookySwap': 'decentralized exchange',
  'Eggs Finance': 'defi protocol',
  'Sonic Whale': 'ai tool',
  'DeBank': 'defi portfolio',
  'DexScreener': 'crypto charts',
  'Ruggie\'s Pizza': 'web3 game',
  'deBridge Finance': 'defi bridge',
  'Silo Finance': 'defi lending',
  'Avalon Labs': 'web3 venture',
  'Aave': 'defi lending',
  'Vicuna Finance': 'defi protocol',
  'Curve': 'defi protocol',
  'Yearn Finance': 'defi yield',
  'Stryke': 'defi options',
  'Rings Money': 'defi protocol',
  'MachFi': 'defi protocol',
  'SilverSwap': 'decentralized exchange',
  'YEL Finance': 'yield farming',
  'MarginZero': 'defi trading',
  'Thunderdome': 'web3 game',
  'Kyber Network': 'decentralized exchange',
  'Krown Labs': 'web3 development',
  'Origin Protocol': 'defi protocol',
  'Curve (Sonic)': 'decentralized exchange',
  'Chainspect': 'blockchain explorer',
  'Rhino.fi': 'defi bridge',
  'Snapshot': 'decentralized voting',
  'Odos': 'dex aggregator',
  'Alchemy': 'web3 development',
  'Summer.fi': 'defi protocol',
  'Micro3': 'socialfi platform',
  'Tenderly': 'development platform',
  'Eliteness': 'social network',
  'Multisender': 'crypto tool',
  'Magpie': 'yield farming',
  'Sushi (Sonic)': 'decentralized exchange',
  'Yoko': 'live streaming',
  'Arkham': 'blockchain intelligence',
  'Spectra': 'yield farming',
  'TRM Labs': 'crypto compliance',
  'Euler Finance': 'defi lending',
  'Napier Finance': 'defi protocol',
  'sNFT': 'nft protocol',
  'LND Fi': 'defi protocol',
  'WooFi': 'decentralized exchange',
  'OnFinality': 'node service',
  'Chainsight': 'oracle network',
  'Ichi': 'defi protocol',
  'Lynx Finance': 'defi protocol',
  'OpenOcean': 'dex aggregator',
  'Biconomy': 'web3 infrastructure',
  'Solv Finance': 'defi protocol',
  'ZNS Connect': 'name service',
  'Owlto Finance': 'defi bridge',
  'Project Zero': 'web3 project',
  'Beefy': 'yield aggregator',
  'Safe': 'multi-sig wallet',
  'MCLB': 'defi protocol',
  'DexFi': 'decentralized exchange',
  'EncLabs Finance': 'defi protocol',
  'Band Protocol': 'oracle network',
  'Envio': 'development tool',
  'SideShift.ai': 'ai swap',
  'SuperSonic': 'decentralized exchange',
  'Stargate Finance': 'defi bridge',
  'Frax Finance': 'stablecoin protocol',
  'Astrolescent': 'defi bridge',
  'Meson': 'defi bridge',
  'Estfor': 'web3 game',
  'CrossCurve': 'cross-chain swap',
  'SimpleSwap': 'crypto exchange',
  'Bungee': 'defi bridge',
  'Gamma': 'liquidity management',
  'LlamaPay': 'payment protocol',
  'Gasp': 'defi bridge',
  'Solidly': 'decentralized exchange',
  'Fireblocks': 'crypto custody',
  'Sonic Market': 'nft marketplace',
  'Layer3': 'web3 quests',
  'Oku Trade': 'decentralized exchange',
  'TokenPocket': 'crypto wallet',
  'Portals': 'defi dashboard',
  'Yelay': 'defi protocol',
  'Paladin': 'governance protocol',
  'Perq Finance': 'defi protocol',
  'BlazingBot': 'trading bot',
  'Vertex Protocol': 'decentralized exchange',
  'vfat.tools': 'yield farming',
  'OpenBlock Labs': 'web3 research',
  'Symbiosis': 'defi bridge',
  'Pendle Finance': 'yield trading',
  'Blockchain Bureau': 'crypto education',
  'Sacra Game': 'web3 game',
  'Avalon Finance': 'defi protocol',
  'fMoney Market': 'money market',
  'Sparta': 'defi protocol',
  'Allora Network': 'ai network',
  'Swaps.io': 'crypto exchange',
  'Router Nitro': 'cross-chain bridge',
  'Dune': 'crypto analytics',
  'Sentio': 'development platform',
  'Orderly Network': 'defi protocol',
  'Amped Finance': 'defi protocol',
  'Steer Finance': 'liquidity management',
  'NFTs2Me': 'nft creation',
  'Lazy Bear': 'nft project',
  'Angles': 'stablecoin protocol',
  'HyperSonic Exchange': 'decentralized exchange',
  'Web3Auth': 'authentication service',
  'Rubic': 'cross-chain swap',
};
