
import type { App } from './types';

export const defaultApps: App[] = [
  { id: 'sonic-1', name: 'Sonic', url: 'https://www.sonic.tech', iconUrl: 'https://www.google.com/s2/favicons?domain=sonic.tech&sz=256', category: 'Infrastructure', isCustom: false, isFavorite: true },
  { id: 'sonic-2', name: 'Rings', url: 'https://rings.money', iconUrl: 'https://www.google.com/s2/favicons?domain=rings.money&sz=256', category: 'DeFi', isCustom: false, isFavorite: true },
  { id: 'sonic-3', name: 'Saga', url: 'https://www.saga.xyz/', iconUrl: 'https://www.google.com/s2/favicons?domain=saga.xyz&sz=256', category: 'Infrastructure', isCustom: false, isFavorite: true },
  { id: 'sonic-4', name: 'Galxe', url: 'https://galxe.com', iconUrl: 'https://www.google.com/s2/favicons?domain=galxe.com&sz=256', category: 'Social', isCustom: false, isFavorite: true },
  { id: 'sonic-5', name: 'LayerZero', url: 'https://layerzero.network', iconUrl: 'https://www.google.com/s2/favicons?domain=layerzero.network&sz=256', category: 'Infrastructure', isCustom: false, isFavorite: true },
  { id: 'sonic-6', name: 'Pyth Network', url: 'https://pyth.network', iconUrl: 'https://www.google.com/s2/favicons?domain=pyth.network&sz=256', category: 'Oracle', isCustom: false, isFavorite: false },
  { id: 'sonic-7', name: 'Band Protocol', url: 'https://www.bandprotocol.com', iconUrl: 'https://www.google.com/s2/favicons?domain=bandprotocol.com&sz=256', category: 'Oracle', isCustom: false, isFavorite: false },
  { id: 'sonic-8', name: 'BounceBit', url: 'https://bouncebit.io', iconUrl: 'https://www.google.com/s2/favicons?domain=bouncebit.io&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-9', name: 'Jupiter', url: 'https://jup.ag', iconUrl: 'https://www.google.com/s2/favicons?domain=jup.ag&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-10', name: 'Wormhole', url: 'https://wormhole.com', iconUrl: 'https://www.google.com/s2/favicons?domain=wormhole.com&sz=256', category: 'Bridge', isCustom: false, isFavorite: false },
  { id: 'sonic-11', name: 'Degen', url: 'https://www.degen.tips', iconUrl: 'https://www.google.com/s2/favicons?domain=degen.tips&sz=256', category: 'Memes', isCustom: false, isFavorite: false },
  { id: 'sonic-12', name: 'Sacra', url: 'https://sacra.game', iconUrl: 'https://www.google.com/s2/favicons?domain=sacra.game&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: true },
  { id: 'sonic-13', name: 'Estfor Kingdom', url: 'https://estfor.com', iconUrl: 'https://www.google.com/s2/favicons?domain=estfor.com&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-14', name: 'Farcana', url: 'https://www.farcana.com', iconUrl: 'https://www.google.com/s2/favicons?domain=farcana.com&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-15', name: 'zkSync', url: 'https://zksync.io', iconUrl: 'https://www.google.com/s2/favicons?domain=zksync.io&sz=256', category: 'L2', isCustom: false, isFavorite: false },
  { id: 'sonic-16', name: 'EigenLayer', url: 'https://www.eigenlayer.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=eigenlayer.xyz&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-17', name: 'Ethena', url: 'https://www.ethena.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=ethena.fi&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-18', name: 'Circle', url: 'https://www.circle.com', iconUrl: 'https://www.google.com/s2/favicons?domain=circle.com&sz=256', category: 'Stablecoin', isCustom: false, isFavorite: false },
  { id: 'sonic-19', name: 'Chainlink', url: 'https://chain.link', iconUrl: 'https://www.google.com/s2/favicons?domain=chain.link&sz=256', category: 'Oracle', isCustom: false, isFavorite: false },
  { id: 'sonic-20', name: 'Lido', url: 'https://lido.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=lido.fi&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-21', name: 'Safe', url: 'https://safe.global', iconUrl: 'https://www.google.com/s2/favicons?domain=safe.global&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-22', name: 'Degen Express', url: 'https://degen.express', iconUrl: 'https://www.google.com/s2/favicons?domain=degen.express&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-23', name: 'Shadow Exchange', url: 'https://shadow.so', iconUrl: 'https://www.google.com/s2/favicons?domain=shadow.so&sz=256', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-24', name: 'SwapX', url: 'https://swapx.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=swapx.fi&sz=256', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-25', name: 'Metropolis', url: 'https://metropolis.exchange', iconUrl: 'https://www.google.com/s2/favicons?domain=metropolis.exchange&sz=256', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-26', name: 'Beets', url: 'https://beets.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=beets.fi&sz=256', category: 'Dex', isCustom: false, isFavorite: false },
  { id: 'sonic-27', name: 'PaintSwap', url: 'https://paintswap.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=paintswap.finance&sz=256', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-28', name: 'Worldcoin', url: 'https://worldcoin.org', iconUrl: 'https://www.google.com/s2/favicons?domain=worldcoin.org&sz=256', category: 'Identity', isCustom: false, isFavorite: false },
  { id: 'sonic-29', name: 'Axelar', url: 'https://axelar.network', iconUrl: 'https://www.google.com/s2/favicons?domain=axelar.network&sz=256', category: 'Bridge', isCustom: false, isFavorite: false },
  { id: 'sonic-30', name: 'friend.tech', url: 'https://www.friend.tech', iconUrl: 'https://www.google.com/s2/favicons?domain=friend.tech&sz=256', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-31', name: 'Pendle', url: 'https://www.pendle.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=pendle.finance&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-32', name: 'Renzo', url: 'https://www.renzoprotocol.com', iconUrl: 'https://www.google.com/s2/favicons?domain=renzoprotocol.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-33', name: 'Kelp DAO', url: 'https://www.kelpdao.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=kelpdao.xyz&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-34', name: 'Ether.fi', url: 'https://www.ether.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=ether.fi&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-35', name: 'Celestia', url: 'https://celestia.org', iconUrl: 'https://www.google.com/s2/favicons?domain=celestia.org&sz=256', category: 'Infrastructure', isCustom: false, isFavorite: false },
  { id: 'sonic-36', name: 'Uniswap', url: 'https://uniswap.org', iconUrl: 'https://www.google.com/s2/favicons?domain=uniswap.org&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-37', name: 'Aave', url: 'https://aave.com', iconUrl: 'https://www.google.com/s2/favicons?domain=aave.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-38', name: 'Curve', url: 'https://curve.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=curve.fi&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-39', name: 'SushiSwap', url: 'https://sushi.com', iconUrl: 'https://www.google.com/s2/favicons?domain=sushi.com&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-40', name: 'PancakeSwap', url: 'https://pancakeswap.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=pancakeswap.finance&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-41', name: 'GMX', url: 'https://gmx.io', iconUrl: 'https://www.google.com/s2/favicons?domain=gmx.io&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-42', name: 'Trader Joe', url: 'https://traderjoexyz.com', iconUrl: 'https://www.google.com/s2/favicons?domain=traderjoexyz.com&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-43', name: 'Velodrome', url: 'https://velodrome.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=velodrome.finance&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-44', name: 'LogX', url: 'https://logx.trade', iconUrl: 'https://www.google.com/s2/favicons?domain=logx.trade&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-45', name: 'Zeta Markets', url: 'https://zetamarkets.com', iconUrl: 'https://www.google.com/s2/favicons?domain=zetamarkets.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-46', name: 'OpenSea', url: 'https://opensea.io', iconUrl: 'https://www.google.com/s2/favicons?domain=opensea.io&sz=256', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-47', name: 'Blur', url: 'https://blur.io', iconUrl: 'https://www.google.com/s2/favicons?domain=blur.io&sz=256', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-48', name: 'Magic Eden', url: 'https://magiceden.io', iconUrl: 'https://www.google.com/s2/favicons?domain=magiceden.io&sz=256', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-49', name: 'The Sandbox', url: 'https://sandbox.game', iconUrl: 'https://www.google.com/s2/favicons?domain=sandbox.game&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-50', name: 'Decentraland', url: 'https://decentraland.org', iconUrl: 'https://www.google.com/s2/favicons?domain=decentraland.org&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-51', name: 'Axie Infinity', url: 'https://axieinfinity.com', iconUrl: 'https://www.google.com/s2/favicons?domain=axieinfinity.com&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-52', name: 'Illuvium', url: 'https://illuvium.io', iconUrl: 'https://www.google.com/s2/favicons?domain=illuvium.io&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-53', name: 'Infura', url: 'https://infura.io', iconUrl: 'https://www.google.com/s2/favicons?domain=infura.io&sz=256', category: 'Infrastructure', isCustom: false, isFavorite: false },
  { id: 'sonic-54', name: 'Alchemy', url: 'https://alchemy.com', iconUrl: 'https://www.google.com/s2/favicons?domain=alchemy.com&sz=256', category: 'Infrastructure', isCustom: false, isFavorite: false },
  { id: 'sonic-55', name: 'Etherscan', url: 'https://etherscan.io', iconUrl: 'https://www.google.com/s2/favicons?domain=etherscan.io&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-56', name: 'MetaMask', url: 'https://metamask.io', iconUrl: 'https://www.google.com/s2/favicons?domain=metamask.io&sz=256', category: 'Wallet', isCustom: false, isFavorite: false },
  { id: 'sonic-57', name: 'Rabby Wallet', url: 'https://rabby.io', iconUrl: 'https://www.google.com/s2/favicons?domain=rabby.io&sz=256', category: 'Wallet', isCustom: false, isFavorite: false },
  { id: 'sonic-58', name: 'Zerion', url: 'https://zerion.io', iconUrl: 'https://www.google.com/s2/favicons?domain=zerion.io&sz=256', category: 'Wallet', isCustom: false, isFavorite: false },
  { id: 'sonic-59', name: 'Zapper', url: 'https://zapper.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=zapper.xyz&sz=256', category: 'Wallet', isCustom: false, isFavorite: false },
  { id: 'sonic-60', name: 'DeBank', url: 'https://debank.com', iconUrl: 'https://www.google.com/s2/favicons?domain=debank.com&sz=256', category: 'Wallet', isCustom: false, isFavorite: false },
  { id: 'sonic-61', name: 'CoinGecko', url: 'https://coingecko.com', iconUrl: 'https://www.google.com/s2/favicons?domain=coingecko.com&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-62', name: 'CoinMarketCap', url: 'https://coinmarketcap.com', iconUrl: 'https://www.google.com/s2/favicons?domain=coinmarketcap.com&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-63', name: 'DefiLlama', url: 'https://defillama.com', iconUrl: 'https://www.google.com/s2/favicons?domain=defillama.com&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-64', name: 'Lens Protocol', url: 'https://lens.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=lens.xyz&sz=256', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-65', name: 'CyberConnect', url: 'https://cyberconnect.me', iconUrl: 'https://www.google.com/s2/favicons?domain=cyberconnect.me&sz=256', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-66', name: 'Orbiter Finance', url: 'https://orbiter.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=orbiter.finance&sz=256', category: 'Bridge', isCustom: false, isFavorite: false },
  { id: 'sonic-67', name: 'Stargate', url: 'https://stargate.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=stargate.finance&sz=256', category: 'Bridge', isCustom: false, isFavorite: false },
  { id: 'sonic-68', name: 'Arbitrum', url: 'https://arbitrum.io', iconUrl: 'https://www.google.com/s2/favicons?domain=arbitrum.io&sz=256', category: 'L2', isCustom: false, isFavorite: false },
  { id: 'sonic-69', name: 'Optimism', url: 'https://optimism.io', iconUrl: 'https://www.google.com/s2/favicons?domain=optimism.io&sz=256', category: 'L2', isCustom: false, isFavorite: false },
  { id: 'sonic-70', name: 'Polygon', url: 'https://polygon.technology', iconUrl: 'https://www.google.com/s2/favicons?domain=polygon.technology&sz=256', category: 'L2', isCustom: false, isFavorite: false },
  { id: 'sonic-71', name: '1inch', url: 'https://1inch.io', iconUrl: 'https://www.google.com/s2/favicons?domain=1inch.io&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-72', name: 'Matcha', url: 'https://matcha.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=matcha.xyz&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-73', name: 'Paraswap', url: 'https://paraswap.io', iconUrl: 'https://www.google.com/s2/favicons?domain=paraswap.io&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-74', name: 'Gearbox', url: 'https://gearbox.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=gearbox.fi&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-75', name: 'Yield Yak', url: 'https://yieldyak.com', iconUrl: 'https://www.google.com/s2/favicons?domain=yieldyak.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-76', name: 'LPB Sonic', url: 'https://lpbsonic.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=lpbsonic.xyz&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-77', name: 'Heyanon', url: 'https://heyanon.ai', iconUrl: 'https://www.google.com/s2/favicons?domain=heyanon.ai&sz=256', category: 'AI', isCustom: false, isFavorite: false },
  { id: 'sonic-78', name: 'Equalizer', url: 'https://equalizer.exchange', iconUrl: 'https://www.google.com/s2/favicons?domain=equalizer.exchange&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-79', name: 'DeFive', url: 'https://defive.com', iconUrl: 'https://www.google.com/s2/favicons?domain=defive.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-80', name: 'Fly Trade', url: 'https://www.fly.trade', iconUrl: 'https://www.google.com/s2/favicons?domain=fly.trade&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-81', name: 'PaintSwap IO', url: 'https://paintswap.io', iconUrl: 'https://www.google.com/s2/favicons?domain=paintswap.io&sz=256', category: 'NFT', isCustom: false, isFavorite: false },
  { id: 'sonic-82', name: 'Navigator Exchange', url: 'https://www.navigator.exchange', iconUrl: 'https://www.google.com/s2/favicons?domain=navigator.exchange&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-83', name: 'Snake Finance', url: 'https://snake.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=snake.finance&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-84', name: 'Derpe', url: 'https://derpe.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=derpe.xyz&sz=256', category: 'Memes', isCustom: false, isFavorite: false },
  { id: 'sonic-85', name: 'Tin Hat Cat', url: 'https://www.tinhatcat.com', iconUrl: 'https://www.google.com/s2/favicons?domain=tinhatcat.com&sz=256', category: 'Memes', isCustom: false, isFavorite: false },
  { id: 'sonic-86', name: 'Goglz', url: 'https://goglz.io', iconUrl: 'https://www.google.com/s2/favicons?domain=goglz.io&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-87', name: 'Wagmi', url: 'https://wagmi.com', iconUrl: 'https://www.google.com/s2/favicons?domain=wagmi.com&sz=256', category: 'Development', isCustom: false, isFavorite: false },
  { id: 'sonic-88', name: 'Spinit', url: 'https://spinit.owl.games', iconUrl: 'https://www.google.com/s2/favicons?domain=spinit.owl.games&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-89', name: 'FaGame', url: 'https://fagame.org', iconUrl: 'https://www.google.com/s2/favicons?domain=fagame.org&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-90', name: 'Boom Markets', url: 'https://boom.markets', iconUrl: 'https://www.google.com/s2/favicons?domain=boom.markets&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-91', name: '8finity', url: 'https://8finity.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=8finity.xyz&sz=256', category: 'Utilities', isCustom: false, isFavorite: false },
  { id: 'sonic-92', name: 'Stability Farm', url: 'https://stability.farm', iconUrl: 'https://www.google.com/s2/favicons?domain=stability.farm&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-93', name: 'Lumos Coin', url: 'https://lumoscoin.com', iconUrl: 'https://www.google.com/s2/favicons?domain=lumoscoin.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-94', name: 'SNS', url: 'https://sns.net', iconUrl: 'https://www.google.com/s2/favicons?domain=sns.net&sz=256', category: 'Social', isCustom: false, isFavorite: false },
  { id: 'sonic-95', name: 'Hedgy Sonic', url: 'https://hedgysonic.com', iconUrl: 'https://www.google.com/s2/favicons?domain=hedgysonic.com&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-96', name: 'Indisonic', url: 'https://www.indisonic.xyz', iconUrl: 'https://www.google.com/s2/favicons?domain=indisonic.xyz&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-97', name: 'Myrd Sacra', url: 'https://myrd.sacra.game', iconUrl: 'https://www.google.com/s2/favicons?domain=sacra.game&sz=256', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: 'sonic-98', name: 'SpookySwap', url: 'https://www.spooky.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=spooky.fi&sz=256', category: 'DEX', isCustom: false, isFavorite: false },
  { id: 'sonic-99', name: 'Eggs Finance', url: 'https://eggs.finance', iconUrl: 'https://www.google.com/s2/favicons?domain=eggs.finance&sz=256', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: 'sonic-100', name: 'Sonic Whale', url: 'https://sonicwhale.ai', iconUrl: 'https://www.google.com/s2/favicons?domain=sonicwhale.ai&sz=256', category: 'AI', isCustom: false, isFavorite: false },
];

export const appHints: Record<string, string> = {
  'Sonic': 'blockchain infrastructure',
  'Rings': 'defi protocol',
  'Saga': 'web3 infrastructure',
  'Galxe': 'social identity',
  'LayerZero': 'omnichain protocol',
  'Pyth Network': 'oracle defi',
  'Band Protocol': 'oracle defi',
  'BounceBit': 'bitcoin restaking',
  'Jupiter': 'dex aggregator',
  'Wormhole': 'crypto bridge',
  'Degen': 'meme coin',
  'Sacra': 'web3 game',
  'Estfor Kingdom': 'web3 game',
  'Farcana': 'web3 game',
  'zkSync': 'layer 2',
  'EigenLayer': 'restaking protocol',
  'Ethena': 'synthetic dollar',
  'Circle': 'usdc stablecoin',
  'Chainlink': 'oracle network',
  'Lido': 'liquid staking',
  'Safe': 'crypto wallet',
  'Degen Express': 'token trading',
  'Shadow Exchange': 'decentralized exchange',
  'SwapX': 'decentralized exchange',
  'Metropolis': 'decentralized exchange',
  'Beets': 'decentralized exchange',
  'PaintSwap': 'nft marketplace',
  'Worldcoin': 'crypto identity',
  'Axelar': 'crypto bridge',
  'friend.tech': 'social crypto',
  'Pendle': 'yield trading',
  'Renzo': 'liquid restaking',
  'Kelp DAO': 'liquid restaking',
  'Ether.fi': 'liquid staking',
  'Celestia': 'modular blockchain',
  'Uniswap': 'decentralized exchange',
  'Aave': 'lending protocol',
  'Curve': 'stablecoin dex',
  'SushiSwap': 'decentralized exchange',
  'PancakeSwap': 'decentralized exchange',
  'GMX': 'perpetual exchange',
  'Trader Joe': 'decentralized exchange',
  'Velodrome': 'amm defi',
  'LogX': 'perpetual exchange',
  'Zeta Markets': 'derivatives platform',
  'OpenSea': 'nft marketplace',
  'Blur': 'nft marketplace',
  'Magic Eden': 'nft marketplace',
  'The Sandbox': 'metaverse game',
  'Decentraland': 'metaverse world',
  'Axie Infinity': 'web3 game',
  'Illuvium': 'web3 game',
  'Infura': 'web3 api',
  'Alchemy': 'web3 developer',
  'Etherscan': 'blockchain explorer',
  'MetaMask': 'crypto wallet',
  'Rabby Wallet': 'crypto wallet',
  'Zerion': 'defi wallet',
  'Zapper': 'defi dashboard',
  'DeBank': 'defi wallet',
  'CoinGecko': 'crypto prices',
  'CoinMarketCap': 'crypto prices',
  'DefiLlama': 'defi dashboard',
  'Lens Protocol': 'social graph',
  'CyberConnect': 'social network',
  'Orbiter Finance': 'crypto bridge',
  'Stargate': 'omnichain bridge',
  'Arbitrum': 'layer 2',
  'Optimism': 'layer 2',
  'Polygon': 'layer 2',
  '1inch': 'dex aggregator',
  'Matcha': 'dex aggregator',
  'Paraswap': 'dex aggregator',
  'Gearbox': 'leverage protocol',
  'Yield Yak': 'yield optimizer',
  'LPB Sonic': 'defi protocol',
  'Heyanon': 'ai social',
  'Equalizer': 'decentralized exchange',
  'DeFive': 'defi protocol',
  'Fly Trade': 'decentralized exchange',
  'PaintSwap IO': 'nft marketplace',
  'Navigator Exchange': 'decentralized exchange',
  'Snake Finance': 'defi protocol',
  'Derpe': 'meme coin',
  'Tin Hat Cat': 'meme coin',
  'Goglz': 'web3 utilities',
  'Wagmi': 'web3 developer',
  'Spinit': 'web3 game',
  'FaGame': 'web3 game',
  'Boom Markets': 'defi trading',
  '8finity': 'web3 platform',
  'Stability Farm': 'defi yield',
  'Lumos Coin': 'crypto coin',
  'SNS': 'social name service',
  'Hedgy Sonic': 'defi protocol',
  'Indisonic': 'defi protocol',
  'Myrd Sacra': 'web3 game',
  'SpookySwap': 'decentralized exchange',
  'Eggs Finance': 'defi protocol',
  'Sonic Whale': 'ai tool'
};
