
import type { App } from './types';

export const defaultApps: App[] = [
  { id: '1', name: 'Notion', url: 'https://notion.so', iconUrl: 'https://icon.horse/icon/notion.so', category: 'Productivity', isCustom: false, isFavorite: true },
  { id: '2', name: 'Slack', url: 'https://slack.com', iconUrl: 'https://icon.horse/icon/slack.com', category: 'Productivity', isCustom: false, isFavorite: true },
  { id: '4', name: 'Figma', url: 'https://figma.com', iconUrl: 'https://icon.horse/icon/figma.com', category: 'Design', isCustom: false, isFavorite: true },
  { id: '8', name: 'Spotify', url: 'https://spotify.com', iconUrl: 'https://icon.horse/icon/spotify.com', category: 'Entertainment', isCustom: false, isFavorite: true },
  { id: '9', name: 'GitHub', url: 'https://github.com', iconUrl: 'https://icon.horse/icon/github.com', category: 'Development', isCustom: false, isFavorite: true },
  { id: '12', name: 'YouTube', url: 'https://youtube.com', iconUrl: 'https://icon.horse/icon/youtube.com', category: 'Entertainment', isCustom: false, isFavorite: false },
  { id: '13', name: 'Uniswap', url: 'https://app.uniswap.org', iconUrl: 'https://icon.horse/icon/uniswap.org', category: 'Dex', isCustom: false, isFavorite: true },
  { id: '14', name: 'Coinbase', url: 'https://www.coinbase.com', iconUrl: 'https://icon.horse/icon/coinbase.com', category: 'Cex', isCustom: false, isFavorite: false },
  { id: '15', name: 'Axie Infinity', url: 'https://axieinfinity.com', iconUrl: 'https://icon.horse/icon/axieinfinity.com', category: 'Web3 Games', isCustom: false, isFavorite: false },
  { id: '16', name: 'dogwifhat', url: 'https://dogwifcoin.org/', iconUrl: 'https://icon.horse/icon/dogwifcoin.org', category: 'Memes', isCustom: false, isFavorite: false },
  { id: '17', name: 'Beets', url: 'https://beets.fi', iconUrl: 'https://icon.horse/icon/beets.fi', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '18', name: 'Shadow Exchange', url: 'https://www.shadow.so', iconUrl: 'https://icon.horse/icon/shadow.so', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '19', name: 'SwapX', url: 'https://swapx.fi', iconUrl: 'https://www.google.com/s2/favicons?domain=swapx.fi&sz=256', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '20', name: 'Rings', url: 'https://rings.money', iconUrl: 'https://icon.horse/icon/rings.money', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '21', name: 'Origin Protocol', url: 'https://www.originprotocol.com', iconUrl: 'https://icon.horse/icon/originprotocol.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '22', name: 'Pendle', url: 'https://pendle.finance', iconUrl: 'https://icon.horse/icon/pendle.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '23', name: 'Metropolis', url: 'https://metropolis.exchange', iconUrl: 'https://icon.horse/icon/metropolis.exchange', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '24', name: 'Silo Finance', url: 'https://www.silo.finance', iconUrl: 'https://icon.horse/icon/silo.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '25', name: 'Eggs Finance', url: 'https://eggs.finance', iconUrl: 'https://icon.horse/icon/eggs.finance', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '26', name: 'SpookySwap', url: 'https://spookyswap.app', iconUrl: 'https://icon.horse/icon/spookyswap.app', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '27', name: 'Magpie Protocol', url: 'https://magpie.xyz', iconUrl: 'https://icon.horse/icon/magpie.xyz', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '28', name: 'Aave', url: 'https://aave.com', iconUrl: 'https://icon.horse/icon/aave.com', category: 'DeFi', isCustom: false, isFavorite: false },
  { id: '29', name: 'Curve', url: 'https://curve.fi', iconUrl: 'https://icon.horse/icon/curve.fi', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '30', name: '1inch', url: 'https://app.1inch.io', iconUrl: 'https://icon.horse/icon/1inch.io', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '31', name: 'SushiSwap', url: 'https://sushi.com', iconUrl: 'https://icon.horse/icon/sushi.com', category: 'Dex', isCustom: false, isFavorite: false },
  { id: '32', name: 'PancakeSwap', url: 'https://pancakeswap.finance', iconUrl: 'https://icon.horse/icon/pancakeswap.finance', category: 'Dex', isCustom: false, isFavorite: false },
];

export const appHints: Record<string, string> = {
  'Notion': 'notes document',
  'Slack': 'team chat',
  'Figma': 'design tool',
  'Spotify': 'music streaming',
  'GitHub': 'code repository',
  'YouTube': 'video platform',
  'Uniswap': 'decentralized exchange',
  'Coinbase': 'crypto exchange',
  'Axie Infinity': 'blockchain game',
  'dogwifhat': 'meme coin',
  'Beets': 'decentralized exchange',
  'Shadow Exchange': 'decentralized exchange',
  'SwapX': 'decentralized exchange',
  'Rings': 'defi protocol',
  'Origin Protocol': 'defi protocol',
  'Pendle': 'defi protocol',
  'Metropolis': 'decentralized exchange',
  'Silo Finance': 'lending protocol',
  'Eggs Finance': 'defi protocol',
  'SpookySwap': 'decentralized exchange',
  'Magpie Protocol': 'defi protocol',
  'Aave': 'lending protocol',
  'Curve': 'decentralized exchange',
  '1inch': 'dex aggregator',
  'SushiSwap': 'decentralized exchange',
  'PancakeSwap': 'decentralized exchange',
};
